### PR TITLE
Refactor CSS

### LINKED ISSUE #4: Refactor Css
The css used is actually written in the index.html page itself . Remove and make a style.css with the written css. Dont forget to link the respective stylesheet.

### PR DESCRIPTION
**Pull request by jcads**

### CODE REVIEW

**Comment by decon-harsh** [comment]
LGTM , Thanks for your precious time and effort. Appreciated, Can you squash the commits?

**Comment by decon-harsh** [comment]
Peaced merged this, next time remember to squash the commits

**Comment by jcads** [comment]
Thanks, I'll remember that next time because this is my first PR.

**Comment by decon-harsh** [comment]
Congrats on getting your first PR merged

**Pull request merged**
